[variables]
NIXPACKS_PYTHON_VERSION = "3.9"

[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'No build step needed for FastAPI'"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
